service: event-handler

custom:
  stage: ${opt:stage, 'prod'}
  env:
    DEPLOYMENT_BUCKET_NAME: event-handler-deployment

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: ${self:custom.stage}
  environment:
    AWS_ACCOUNT_ID: ${ env:AWS_ACCOUNT_ID }
    SMTP_HOST: ${ssm:/sys/SMTP_HOST}
    SMTP_PORT: ${ssm:/sys/SMTP_PORT}
    SMTP_USERNAME: ${ssm:/sys/SMTP_USERNAME}
    SMTP_PASSWORD: ${ssm:/sys/SMTP_PASSWORD}
  deploymentBucket:
    name: ${self:custom.env.DEPLOYMENT_BUCKET_NAME}
    serverSideEncryption: AES256
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"

resources:
  Resources:
    DeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: event-handler-deployment
        AccessControl: Private
        
functions:
  eventProcessor:
    handler: src/handlers/eventProcessor.handler
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - "aws.cloudtrail"
            detail-type:
              - "AWS API Call via CloudTrail"
