service: event-handler

provider:
  name: aws
  runtime: nodejs18.x
  region: ${ env:AWS_REGION }
  environment:
    AWS_ACCOUNT_ID: ${ env:AWS_ACCOUNT_ID }
  memorySize: 256
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"

functions:
  eventProcessor:
    handler: src/handlers/eventProcessor.handler
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - "aws.cloudtrail"
            detail-type:
              - "AWS API Call via CloudTrail"
